konferencija/conference/urls.py
from django.conf.urls import url

from .views import (
    ConferenceCreateView,
    ConferenceListView,
    ConferenceDetailView,
    SekcijeView,
    FileCreateView,
    RadoviListView,
    RecenzentListView,
)
urlpatterns = [
    url(r'radovi/(?P<pk>\d+)/$', RadoviListView.as_view(), name='radovi_list'),
    url(r'recenzent_list/(?P<pk>\d+)/$', RecenzentListView.as_view(), name='recenzent_list'),
    url(r'create$', ConferenceCreateView.as_view(), name='create'),
    url(r'create/(?P<pk>\d+)/file/$', FileCreateView.as_view(), name='create_file'),
    url(r'sekcije/(?P<pk>\d+)/$', SekcijeView.as_view(), name = 'sekcija'),
    url(r'(?P<pk>\d+)/$', ConferenceDetailView.as_view(), name = 'detail'),
    url(r'$', ConferenceListView.as_view(), name='custom-list'),
]

konferencija/konferencija/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^messenger/', include(('messenger.urls','messenger'),namespace = 'messenger')),
    url(r'^admin/', admin.site.urls),
    url('conference/', include(('conference.urls','conference'),namespace = 'conference')),
    url('logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    url('^', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

konferencija/messenger/urls.py
from django.conf.urls import url


from . import views
urlpatterns = [
    url(r'(?P<pk>\d+)/$', views.MessageList.as_view(), name='messenger'),
]

konferencija/users/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #Authentication views
    url(r'validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.ActivationView.as_view(),name='activate'),
    url(r'login/$',views.UserLoginView.as_view(),name='login'),
    #Password reset views
    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(template_name='user_reset_confirm.html'),name='password_reset_confirm'),
    url(r'reset/done/$',auth_views.PasswordResetView.as_view(template_name='user_reset_done.html'),name='reset-done'),
    url(r'reset/$',auth_views.PasswordResetView.as_view(template_name='user_reset_password.html',success_url = 'reset/done/'),name='reset-password'),

    #Password change views
    url(r'password-change/$',views.CustomPasswordChangeView.as_view(template_name='user_change_password.html'),name='user-change-password'),
    url(r'password_change/done/$',auth_views.PasswordChangeDoneView.as_view(template_name='user_change_done.html'),name='user-change-done'),

    #User views
    url(r'signup/$', views.UserCreateView.as_view(), name='signup'),
    url(r'update/(?P<pk>\d+)/$', views.UserUpdateView.as_view(), name='update'),
    url(r'detail/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='detail'),
    url(r'list/(?P<pk>\d+)/$', views.UserListView.as_view(), name='user_list'),

    #Home
    url(r'custom-list/$', views.CustomUserListView.as_view(), name='custom_user_list'),
    url(r'$', views.HomePageView.as_view(), name='home'),
]

konferencija/users/models.py
#Django imports
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse_lazy
#Local imports
from . import utils

#Custom user that has email instead as username field
class CustomUser(AbstractUser):
    email = models.EmailField(('email address'), unique=True)
    ulica = models.CharField(max_length = 20)
    kucni_broj = models.CharField(max_length = 20)
    grad = models.CharField(max_length = 20)
    drzava = models.CharField(max_length = 20)
    email_confirmed = models.BooleanField(default=0)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','first_name' ,'last_name']

    def __str__(self):
        list = self.email.split('@')
        return list[0] + '_' + str(self.id)

    def get_absolute_url(self):
        return reverse_lazy('detail', kwargs={'pk': self.pk})



def post_save_reciever(sender,instance,*args,**kwargs):
    if instance.email_confirmed == 0:
        utils.send_mail_to(instance)
    else:
        print('logged in')

models.signals.post_save.connect(post_save_reciever,sender=CustomUser)

konferencija/users/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms
from . import models


class UserCreationForm(auth_forms.UserCreationForm):
    class Meta(auth_forms.UserCreationForm):
        model = models.CustomUser
        fields = ('username','first_name' ,'last_name', 'email','ulica','kucni_broj','grad','drzava')
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class UserAuthenticationForm(auth_forms.AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                ("This account is inactive."),
                code='inactive',
            )
        if not user.email_confirmed:
            raise forms.ValidationError(
                ("Sorry, you need to confirm your email."),
                code='emial_not_confirmed',
            )
    def __init__(self, *args, **kwargs):
        super(UserAuthenticationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

konferencija/users/views.py
#View imports
from django.views import generic
#Rendering imports
from django.urls import reverse_lazy
from django import http
#Query imports
from django.db.models import Q
#Other django imports
from django.contrib.auth import get_user_model, views as auth_views
from django.contrib.auth.tokens import default_token_generator
#Other imports
from django.utils.encoding import force_bytes
from django.utils import http as safehttp
from django.contrib.auth.mixins import LoginRequiredMixin

#Local imports
from . import forms
#Outside app imports
from conference import models





class HomePageView(generic.ListView):
    template_name = "home.html"
    def get_queryset(self):
        return models.Konferencija.objects.all()

#User Views
class UserCreateView(generic.CreateView):
    form_class = forms.UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'user_create.html'

class UserUpdateView(LoginRequiredMixin,generic.edit.UpdateView):
    template_name = 'user_update.html'
    model = get_user_model()
    login_url = reverse_lazy('login')
    fields = ['first_name','last_name','ulica','grad','username']
    def get_success_url(self, **kwargs):
        return reverse_lazy('detail', kwargs = {'pk': self.kwargs['pk']})

class UserListView(LoginRequiredMixin,generic.ListView):
    context_object_name = 'user_list'
    template_name = 'user_list.html'
    login_url = reverse_lazy('login')
    def get_queryset(self):
        sekcije = models.Sekcija.objects.filter(konferencija_id = self.kwargs['pk']).all()
        queryset = models.User_Sekcija.objects.filter(sekcija__in = sekcije).values('user').distinct()
        user_model = get_user_model()
        list =  []
        for i in queryset.all():
            if(int(i['user'])!=self.request.user.id):
                list.append(int(i['user']))
        queryset = user_model.objects.filter(id__in = list)
        return queryset

class CustomUserListView(generic.ListView):
    context_object_name = 'konf_list'
    template_name = 'custom_user_list.html'
    login_url = reverse_lazy('login')
    def get_queryset(self):
        konferencije = models.User_Sekcija.objects.filter(Q(user_id = self.request.user.id) & ~Q(sekcija__konferencija__chairman_id = self.request.user.id)).values('sekcija__konferencija_id').distinct()
        queryset = models.Konferencija.objects.filter(id__in = konferencije)
        return queryset

class UserDetailView(LoginRequiredMixin,generic.DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    login_url = reverse_lazy('login')

#Authentication views

class UserLoginView(auth_views.LoginView):
    form_class = forms.UserAuthenticationForm
    template_name = 'user_login.html'
    def get_success_url(self, **kwargs):
        return reverse_lazy('home')


class ActivationView(generic.View):
    #Activates user account and redirects to login
    def get(self, request, *args, **kwargs):
        uidb64 = self.kwargs['uidb64']
        token = self.kwargs['token']
        if uidb64 is not None and token is not None:
            uid = safehttp.urlsafe_base64_decode(uidb64)
            user_model = get_user_model()
            user = user_model.objects.get(pk=uid)
            valid = default_token_generator.check_token(user, token)
            try:
                if valid and not request.user.is_authenticated:
                    if user.email_confirmed == 0:
                        user_model.objects.filter(pk=uid).update(email_confirmed = 1)
                        return http.HttpResponseRedirect(reverse_lazy('login'))
                else:
                    return http.HttpResponseRedirect(reverse_lazy('home'))
            except Exception as e:
                print(e)

        return http.HttpResponseRedirect('/')

class CustomPasswordChangeView(LoginRequiredMixin,auth_views.PasswordChangeView):
    def get_success_url(self, **kwargs):
        return reverse_lazy('home')

konferencija/users/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/templates/static/css/modern-business.css?{% now "U" %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <title>Django Templates Tutorial</title>
</head>
<body class="body">
  <div class="wrapper">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="nav-custom">
      <div class="container">
        {% if not request.user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'home' %}">Speakers Corner</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                {% if request.user.is_superuser %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'conference:create' %}">Create</a>
                </li>
                {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'custom_user_list' %}">Messenger</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'conference:custom-list' %}">My conferences</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'detail' request.user.id %}">Account</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Signup</a>
              </li>
              {% endif %}
          </ul>
        </div>
      </div>
  </nav>
  {% block content %}
  {% endblock %}
  </div>
  <footer class="bg-dark navbar-fixed-bottom py-2" >
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
    </div>
    <!-- /.container -->
  </footer>
</body>
<!-- Footer -->

<!-- Bootstrap core JavaScript -->

</html>

konferencija/users/templates/custom_user_list.html
{% extends "base.html" %}

{% block content %}
<div class="empty-space">
</div>
<div class="container">
  <div class="row mb-5">
    <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Messenger</h2>
        <h4 class="section-subheading text-muted">Contact any conference chairman.</h4>
    </div>
  </div>
  <input type="text" class="form-control search" placeholder="  Search for names..">
  <ul class="list-group list-group-flush scrollable-list">
    {% for obj in konf_list %}
      {% if not request.user == obj %}
          <li class="list-group-item list-group-item-action">{{ obj.name|title }} <a class="float-right" href="{% url 'messenger:messenger' obj.chairman.id %}">Messenger</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</div>
<script>
$(document).ready(function(){
  $(".search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $(".scrollable-list li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% endblock %}

konferencija/users/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<a href="javascript:" id="return-to-top"><i class="fas fa-angle-up"></i></a>
{% if not request.user.is_authenticated %}
<!-- Header -->
<div class="bg">
  <div class="layer">
    <div class="layer-content">
      <p><span>Welcome to Speakers Corner</span></p>
      <p><span>A website for organizing and finding conferences</span></p>
      <button id="scroll-down" class="btn btn-secondary btn-lg">Let's start</button>
    </div>
  </div>
</div>

<div class="container" id="middle">
  <div class="empty-space">
  </div>
</div>
{% endif %}
<!-- Page Content -->
  <div class="container mb-5">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row pt-5 ">
      <div class="offset-md-1 pl-4">
          <h4 class="text-center text-muted">Choose from a large quantity of upcoming conferences.</h4>
      </div>
    </div>
    <div class="row pt-5 offset-md-1">
      <!-- Blog Entries Column -->
      <div class="col-md-10 col-sm-12">
        {% for obj in object_list reversed  %}
        <!-- Blog Post -->
        <div class="card mb-5">
          <img class="card-img-top card-img-style" src="{{ obj.image.url }}" height="400" alt="Card image cap">
          <div class="card-body">
            <h2 class="card-title">{{ obj.name }}</h2>
            <p class="card-text">{{ obj.summary }}</p>
            <a href="{{ obj.get_absolute_url }}" class="btn btn-secondary">
                {% if not request.user.is_authenticated %}
                Read More &rarr;
                {% else %}
                Join
                {% endif %}
            </a>
          </div>
        </div>
        {% endfor %}
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
  </div>
{% if not user.is_authenticated %}
<script type="text/javascript">
  $(document).ready(function(){
    $( "body" ).css("padding-top","0");
    if(document.scrollingElement.scrollTop == 0 ){
      $( ".navbar" ).removeClass("bg-dark");
      $( ".navbar" ).addClass("bg-custom");
    }
    $(window).scroll(function(){
      console.log(document.scrollingElement.scrollTop);
      if(document.scrollingElement.scrollTop == 0 ){
        console.log("here");
        $( ".navbar" ).removeClass("bg-dark");
        $( ".navbar" ).addClass("bg-custom");
      }else if(document.scrollingElement.scrollTop != 0){
        $( ".navbar" ).removeClass("bg-custom");
        $( ".navbar" ).addClass("bg-dark");
      }
    });
    $("#scroll-down").click(function() {
      console.log("click")
      $('html,body').animate({
        scrollTop: $("#middle").offset().top},
        'slow');
      });
});
</script>
{% endif %}
<script type="text/javascript">
  $(document).ready(function(){
    // ===== Scroll to Top ====
  $(window).scroll(function() {
      if ($(this).scrollTop() >= 50) {        // If page is scrolled more than 50px
          $('#return-to-top').fadeIn(200);    // Fade in the arrow
      } else {
          $('#return-to-top').fadeOut(200);   // Else fade out the arrow
      }
  });
  $('#return-to-top').click(function() {      // When arrow is clicked
      $('body,html').animate({
          scrollTop : 0                       // Scroll to top of body
      }, 500);
  });
});
</script>
{% endblock %}

konferencija/users/templates/user_change_done.html
{% extends "base.html" %}

{% block content %}
<p>You have sucesfully changed your password</p>
<p class="s-margin"><a href="{% url home' %}">Home </a></p>
{% endblock %}

konferencija/users/templates/user_change_password.html
{% extends "base.html" %}

{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Contact Form -->
  <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
  <div class="row">
    <div class="col-lg-8 mb-4 pt-5">
      <h3>Send us a Message</h3>
      <form method="post">
        {% csrf_token %}
        <p><label for="id_old_password">Old password:</label> <input class="form-control" type="password" name="old_password" autofocus required id="id_old_password"></p>
        <p><label for="id_new_password1">New password:</label> <input class="form-control" type="password" name="new_password1" required id="id_new_password1"> <span class="helptext"><ul><li>Your password can&#39;t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can&#39;t be a commonly used password.</li><li>Your password can&#39;t be entirely numeric.</li></ul></span></p>
        <p><label for="id_new_password2">New password confirmation:</label> <input class="form-control"type="password" name="new_password2" required id="id_new_password2"></p>
        <input class="btn btn-secondary" type="submit" value="Change">
    </div>

  </div>
  <!-- /.row -->
</div>
<!-- /.container -->
{% endblock %}

konferencija/users/templates/user_create.html
{% extends 'base.html' %}

{% block content %}
<!-- Page Content -->
<div class="container">
  <!-- Contact Form -->
  <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
  <div class="row">
    <div class="col-lg-8 mb-4 pt-5">
      <h3>Sign up</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary" type="submit">Sign up</button>
      </form>
    </div>
  </div>
  <!-- /.row -->
</div>
<!-- /.container -->
{% endblock %}

konferencija/users/templates/user_detail.html
{% extends "base.html" %}

{% block content %}
<!-- Page Content -->
    <div class="container">
      <div class="empty-space">
      </div>
      <div class="row">
        <div class="col-md-5">
          <p><label for="id_email">First Name:</label> <input class="form-control" value="{{ object.first_name }}" disabled></p>
        </div>
      </div>
          <hr>
      <div class="row">
        <div class="col-md-5">
          <p><label for="id_email">Last Name:</label> <input class="form-control" value="{{ object.last_name }}" disabled></p>
        </div>
      </div>
          <hr>
      <div class="row">
        <div class="col-md-5">
          <p><label for="id_email">Username:</label> <input class="form-control" value="{{ object.username }}" disabled></p>
        </div>
      </div>
          <hr>
      <div class="row">
        <div class="col-md-5">
          <p><label for="id_email">Email address:</label> <input class="form-control"  value="{{ object.email }}"disabled></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-5">
          <p><label for="id_ulica">Ulica:</label> <input class="form-control"  value="{{ object.ulica }}"disabled></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-5">
          <p><label for="id_grad">Grad:</label> <input class="form-control"  value="{{ object.grad }}"disabled></p>
        </div>
      </div>
      <hr>
      <a class="btn btn-secondary" href="{% url 'update' object.id %}">Update account
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
      {% if not object != request.user%}
      <a class="btn btn-secondary" href="{% url 'user-change-password' %}">Change password
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
      {% endif %}
      <div class="empty-space">
      </div>
    </div>
    <!-- /.container -->
{% endblock %}

konferencija/users/templates/user_list.html
{% extends "base.html" %}

{% block content %}
<div class="empty-space">
</div>
<div class="container ">
  <h2  class="container mb-5 text-center" >User list</h2>
  <input type="text" class="form-control search" placeholder="  Search for names..">
  <div class="scrollable-list">
    {% for obj in user_list %}
      {% if not request.user == obj %}
      <ul class="list-group list-group-flush">
        <li class="list-group-item list-group-item-action">{{ obj.username|title }}   {{ obj.sekcija.name|title }} <a class="float-right ml-3" href="{{ obj.get_absolute_url }}">Profile</a><a class="float-right" href="{% url 'messenger:messenger' obj.id %}">Messenger</a></li>
      </ul>
      {% endif %}
  {% endfor %}
  </div>
</div>
<script>
$(document).ready(function(){
  $(".search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $(".scrollable-list li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% endblock %}

konferencija/users/templates/user_login.html
{% extends "base.html" %}

{% block content %}

<!-- Page Content -->
<div class="container">
  <div class="container">
    <div class="empty-space">
    </div>
  </div>
  <!-- Contact Form -->
  <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
  <div class="row">
    <div class="col-lg-8 mb-4 pt-5">
      <h2>Login</h2>
      <form method="post" class="mt-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary" type="submit">Login</button><a class="float-right" href="{% url 'reset-password' %}">Reset password </a>
      </form>
    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

{% endblock %}

konferencija/users/templates/user_reset.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <form method="post">
      <p><label for="id_old_password">Old password:</label> <input type="password" name="old_password" autofocus required id="id_old_password"></p>
      <p><label for="id_new_password1">New password:</label> <input type="password" name="new_password1" required id="id_new_password1"> <span class="helptext"><ul><li>Your password can&#39;t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can&#39;t be a commonly used password.</li><li>Your password can&#39;t be entirely numeric.</li></ul></span></p>
      <p><label for="id_new_password2">New password confirmation:</label> <input type="password" name="new_password2" required id="id_new_password2"></p>
      <input class="btn btn-secondary" type="submit" value="Change">
    </form>
    <input class="btn btn-secondary" type="submit" value="Reset">
</form>
{% endblock %}

konferencija/users/templates/user_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="container">
    <div class="empty-space">
    </div>
  </div>
  <form method="post">
    {% csrf_token %}
    <p><label for="id_new_password1">New password:</label> <input class="form-control" type="password" name="new_password1" required id="id_new_password1"> <span class="helptext"><ul><li>Your password can&#39;t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can&#39;t be a commonly used password.</li><li>Your password can&#39;t be entirely numeric.</li></ul></span></p>
    <p><label for="id_new_password2">New password confirmation:</label> <input class="form-control" type="password" name="new_password2" required id="id_new_password2"></p>
    <input class="btn btn-secondary" type="submit" value="Reset">
  </form>
</div>

{% endblock %}

konferencija/users/templates/user_reset_done.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="empty-space">
  </div>
<p>An email has been sent to your account</p>
<div class="empty-space">
</div>
</div>
{% endblock %}

konferencija/users/templates/user_reset_password.html
{% extends "base.html" %}

{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Contact Form -->
  <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
  <div class="row">
      <div class="container" id="middle">
        <div class="empty-space">
        </div>
      </div>
    <div class="col-lg-8 mb-4 pt-5">
      <h3>Reset Password</h3>
      <form method="post" class="mt-4">
        {% csrf_token %}
        <p><label for="id_email">Email:</label> <input class = "form-control" type="email" name="email" maxlength="254" required id="id_email"></p>
        <input class="btn btn-secondary" type="submit" value="Reset">
      </form>
    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->
{% endblock %}

konferencija/users/templates/user_update.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="empty-space">
  </div>
<form method="post">
    {% csrf_token %}
    <p><label for="id_first_name">First Name:</label> <input class="form-control" value="{{ object.first_name }}" type="text" name="first_name"  maxlength="20" required id="id_first_name"></p>
    <p><label for="id_last_name">Last Name:</label> <input class="form-control" value="{{ object.last_name }}" type="text" name="last_name"  maxlength="20" required id="id_last_name"></p>
    <p><label for="id_username">Username:</label> <input class="form-control" value="{{ object.username }}" type="text" name="username" maxlength="150" required id="id_username"> <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span></p>
    <p><label for="id_ulica">Ulica</label> <input class="form-control" value="{{ object.ulica }}" type="ulica" name="ulica"  maxlength="254" required id="id_ulica"></p>
    <p><label for="id_grad">Grad</label> <input class="form-control" value="{{ object.grad }}" type="grad" name="grad"  maxlength="254" required id="id_grad"></p>
    <input class="btn btn-secondary" type="submit" value="Update">
</form>
<div class="empty-space">
</div>
</div>
{% endblock %}