konferencija/conference/urls.py
from django.conf.urls import url

from .views import (
    ConferenceCreateView,
    ConferenceListView,
    ConferenceDetailView,
    SekcijeView,
    FileCreateView,
    RadoviListView,
    RecenzentListView,
)
urlpatterns = [
    url(r'radovi/(?P<pk>\d+)/$', RadoviListView.as_view(), name='radovi_list'),
    url(r'recenzent_list/(?P<pk>\d+)/$', RecenzentListView.as_view(), name='recenzent_list'),
    url(r'create$', ConferenceCreateView.as_view(), name='create'),
    url(r'create/(?P<pk>\d+)/file/$', FileCreateView.as_view(), name='create_file'),
    url(r'sekcije/(?P<pk>\d+)/$', SekcijeView.as_view(), name = 'sekcija'),
    url(r'(?P<pk>\d+)/$', ConferenceDetailView.as_view(), name = 'detail'),
    url(r'$', ConferenceListView.as_view(), name='custom-list'),
]

konferencija/konferencija/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^messenger/', include(('messenger.urls','messenger'),namespace = 'messenger')),
    url(r'^admin/', admin.site.urls),
    url('conference/', include(('conference.urls','conference'),namespace = 'conference')),
    url('logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    url('^', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

konferencija/users/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #Authentication views
    url(r'validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.ActivationView.as_view(),name='activate'),
    url(r'login/$',views.UserLoginView.as_view(),name='login'),
    #Password reset views
    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(template_name='user_reset_confirm.html'),name='password_reset_confirm'),
    url(r'reset/done/$',auth_views.PasswordResetView.as_view(template_name='user_reset_done.html'),name='reset-done'),
    url(r'reset/$',auth_views.PasswordResetView.as_view(template_name='user_reset_password.html',success_url = 'reset/done/'),name='reset-password'),

    #Password change views
    url(r'password-change/$',views.CustomPasswordChangeView.as_view(template_name='user_change_password.html'),name='user-change-password'),
    url(r'password_change/done/$',auth_views.PasswordChangeDoneView.as_view(template_name='user_change_done.html'),name='user-change-done'),

    #User views
    url(r'signup/$', views.UserCreateView.as_view(), name='signup'),
    url(r'update/(?P<pk>\d+)/$', views.UserUpdateView.as_view(), name='update'),
    url(r'detail/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='detail'),
    url(r'list/(?P<pk>\d+)/$', views.UserListView.as_view(), name='user_list'),

    #Home
    url(r'custom-list/$', views.CustomUserListView.as_view(), name='custom_user_list'),
    url(r'$', views.HomePageView.as_view(), name='home'),
]

konferencija/conference/models.py
from django.db import models
from users.models import CustomUser
from django.db.models.signals import pre_save,post_save
from django.urls import reverse

def clearString(str):
    str = ''.join(e for e in str if e.isalnum()).lower().replace('š','s').replace('ć','c').replace('č','c').replace('đ','d').replace('ž','z')
    return str

#Konferencija
class Konferencija(models.Model):
    creator = models.ForeignKey(CustomUser,related_name='related_primary_manual_roats', on_delete=models.CASCADE)
    chairman = models.ForeignKey(CustomUser,related_name='related_secondary_manual_roats', on_delete=models.CASCADE, default = creator)
    name = models.CharField(max_length=100, unique = True)
    description = models.CharField(max_length=4000)
    summary = models.CharField(max_length=2000)
    created = models.DateTimeField(auto_now_add=True)
    sekcije = models.CharField(max_length=120)
    form = models.CharField(max_length = 1000, default = None)
    time = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default="default.jpg")
    REQUIRED_FIELDS = ['creator','chairman','name']
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('conference:detail', kwargs={'pk': self.pk})

class Sekcija(models.Model):
    konferencija = models.ForeignKey(Konferencija, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.konferencija.name + '_' + self.name

    def get_absolute_url(self):
        return reverse('conference:sekcija', kwargs={'pk': self.pk})

class User_Sekcija(models.Model):
    sekcija = models.ForeignKey(Sekcija, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    recenzent_not_approved = models.BooleanField(default=False)
    recenzent_approved =  models.BooleanField(default=False)
    questions = models.CharField(max_length = 1000, default = None)
    class Meta:
        unique_together = ("sekcija", "user")
    def __str__(self):
        return (self.user.email.split('@')[0] + '_' + self.sekcija.konferencija.name + '_' + self.sekcija.name).lower()

def user_directory_path(instance,filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    user_sekcija = ''.join(e for e in instance.user_sekcija.__str__() if e.isalnum())
    filename = ''.join(e for e in filename if e.isalnum())
    string = '{0}'.format(clearString(filename))
    return string

class Radovi(models.Model):
    user_sekcija = models.ForeignKey(User_Sekcija, on_delete=models.CASCADE)
    upload = models.FileField(upload_to=user_directory_path)
    authors = models.CharField(max_length=120)
    title = models.CharField(max_length=120)
    approved = models.IntegerField(default=0)
    time = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user_sekcija.__str__() + '_' + self.title
    def get_absolute_url(self):
        return reverse('conference:radovi_detail', kwargs={'pk': self.pk})

def post_save_reciever(sender,instance,*args,**kwargs):
    for i in instance.sekcije.split(','):
        sekcija = Sekcija.objects.create(konferencija = instance, name = i)
        sekcija.save()

post_save.connect(post_save_reciever,sender=Konferencija)

konferencija/conference/forms.py
from .models import Konferencija,User_Sekcija
from django.forms import ModelForm
from django import forms
from .models import CustomUser,Radovi
class ConferenceForm(ModelForm):
    MODEL_CATEGORIES = (
        ('maths', 'maths'),
        ('history', 'history'),
        ('science', 'science'),
    )
    model_categories = forms.MultipleChoiceField(
            widget = forms.CheckboxSelectMultiple,
            choices = MODEL_CATEGORIES
    )
    chairman = forms.ModelChoiceField(queryset=CustomUser.objects.all())
    description = forms.CharField(widget=forms.Textarea)
    summary = forms.CharField(widget=forms.Textarea)

    #sekcije = forms.MultipleChoiceField(choices=SAMPLE_CHOICES)
    class Meta:
        model = Konferencija
        fields = ['name','chairman','model_categories','image','description','summary']
    def __init__(self, *args, **kwargs):
        super(ConferenceForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class SekcijaForm(ModelForm):
    CHOICES = ((False, 'Normal User'),(True, 'Recenzent'),)
    recenzent = forms.ChoiceField(choices=CHOICES)
    class Meta:
        model = User_Sekcija
        fields = ['recenzent']
    def __init__(self, *args, **kwargs):
        super(SekcijaForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class UploadFileForm(ModelForm):
    def clean(self):
        cleaned_data = super().clean()
    class Meta:
        model = Radovi
        fields = ['upload','title','authors']

konferencija/conference/templates/conference/file_create.html
{% extends 'base.html' %}


{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Contact Form -->
  <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
  <div class="row">
    <div class="col-lg-8 mb-4 pt-5">
      <h3 class="mb-5">Upload file</h3>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p><label for="id_authors">Authors:</label> <input class="form-control" type="text" name="authors" maxlength="120" required id="id_authors"></p>
        <p><label for="id_title">Title:</label> <input class="form-control" type="text" name="title" maxlength="120" required id="id_title"></p>
        <p><label for="id_file">File:</label><input class="form-control-file" accept="application/pdf" type="file" name="upload" required id="id_upload"></p>
        <button class="btn btn-secondary" type="submit">Upload</button>
      </form>
    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->
{% endblock %}

konferencija/conference/templates/conference/konferencija_create.html
{% extends "base.html" %}

{% block content %}
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!-- Page Content -->
<div class="container">

  <!-- Contact Form -->
  <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
  <div class="row">
    <div class="col-lg-8 mb-4 pt-5">
      <h3>Conference Creation</h3>
      <form method="post" enctype="multipart/form-data" class="mt-4">
        {% csrf_token %}
        <p><label for="id_name">Name:</label> {{ form.name }}</p>
        {{ form.name.errors}}
        <p><label class="form-check-label" for="id_chairman">Chairman:</label> {{ form.chairman }}</p>
        <p>
          <label>Model categories:</label>
          <ul id="id_model_categories">
            <li>
              <label class="form-check-label" for="id_model_categories_0">
              <input class="form-check-input" type="checkbox" name="model_categories" value="maths" id="id_model_categories_0">maths</label>
            </li>
            <li>
              <label class="form-check-label" for="id_model_categories_1">
              <input class="form-check-input" type="checkbox" name="model_categories" value="history" id="id_model_categories_1">history</label>
            </li>
            <li>
              <label class="form-check-label" for="id_model_categories_2">
              <input class="form-check-input"  type="checkbox" name="model_categories" value="science" id="id_model_categories_2">science</label>
            </li>
          </ul>
        </p>
        <p><label for="id_description">Description:</label> <textarea rows="4" type="text" name="description" maxlength="4000" class="form-control" required id="id_description"></textarea></p>
        <p><label for="id_summary">Summary:</label> <textarea  rows="3" type="text" name="summary" maxlength="2000" class="form-control" required id="id_summary"></textarea></p>
        <p><label for="id_image">Image:</label> <input  type="file" name="image" accept="image/*" class="file-form-control" required id="id_image"></p>
        {{ form.image.errors}}
        <div id="field">
          <div class="input-group mb-3" id="group-input-1">
            <input autocomplete="off" class="input form-control" name="question" type="text" placeholder="Type question" data-items="8"/>
            <div class="input-group-append" id="group1">
              <button id="btn-append" class="btn btn-secondary" type="button">+</button>
            </div>
          </div>
        </div>
        <button class="btn btn-secondary" type="submit">Create</button>
      </form>
    </div>

  </div>
  <!-- /.row -->


</div>
<!-- /.container -->
<script type="text/javascript">
  $(document).ready(function(){
    var next = 1;
    $("#field").on("click", "#btn-append", function(e){
        e.preventDefault();
        var groupId = "#group"+next
        var appendButton = $("#btn-append")
        var removeButton = '<button id="btn-remove-' + next + '" class="btn btn-remove btn-secondary" type="button">-</button>'
        next = next + 1
        var newInput = '<div class="input-group mb-3" id="group-input-'+ next + '"><input autocomplete="off" class="input form-control" name="question" type="text" placeholder="Type questions" data-items="8"/><div class="input-group-append" id="group' + next +'"><button id="btn-append" class="btn btn-secondary" type="button">+</button></div></div>'
        $("#btn-append").remove()
        $(groupId).append(removeButton)
        $("#field").append(newInput)
    });
    $("#field").on("click", ".btn-remove", function(e){
      var id = e.target.id.split("-")[2]
      $("#group-input-"+id).remove()
    });
});

</script>
{% endblock %}

konferencija/conference/templates/conference/konferencija_detail.html
{% extends 'base.html' %}

{% block content %}
<!-- Page Content -->
    <div class="container">

      <!-- Page Heading/Breadcrumbs -->
      {% if request.user.is_authenticated %}
      <h1 class="mt-4 mb-3 pt-3 pb-3 " >{{ object.name|title }}
      </h1>
      {% else %}
      <h1 class="mt-4 mb-3 pt-3 pb-3 text-center" >{{ object.name|title }}
      </h1>
      {% endif %}
      <div class="row">

        <!-- Post Content Column -->
        {% if request.user.is_authenticated %}
        <div class="col-lg-8">
        {% else %}
        <div class="col-lg-8 offset-md-2">
        {% endif %}
          <!-- Preview Image -->
          <img class="img-fluid rounded pb-3" src="{{ object.image.url }}" alt="">

          <hr>

          <!-- Date/Time -->
          <p>Posted on {{ object.time }}</p>
          <hr>
          <!-- Post Content -->
          <p>{{ object.description }}</p>
          <hr>
          <br>
          <br>
        </div>
        {% if request.user.is_authenticated %}
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">
          <div class="card">
            <h5 class="card-header">Sections</h5>
            <ul class="list-group list-group-flush mb-0 pl-4">
              {% for key, value in dict %}
                  <li class="list-group-item"><a href="{{ key.get_absolute_url }}">{{ key.name|title }}</a>
                  {% if value %}
                  <span>[ Recenzent ]</span>
                  {% endif %}
                  </li>
              {% endfor %}
            </ul>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Summary</h5>
            <div class="card-body">
              {{ object.summary }}
            </div>
          </div>
          {% if object.chairman == request.user or request.user.is_superuser %}
          <div class="card my-4">
            <h5 class="card-header">Administration</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                        <li><a href="{% url 'user_list' konferencija.id %}">Users</a></li>
                        <li><a href="{% url 'conference:recenzent_list' konferencija.id %}">Recenzenti</a></li>
                  </ul>
                </div>
                <div class="col-lg-6">
                </div>
              </div>
            </div>
          </div>
          {% endif %}

        </div>
        {% endif %}

      </div>
      <!-- /.row -->

    </div>
    <script type="text/javascript">
      $(document).ready(function(){
        console.log('Hello');
        $('.toast').toast();
      });
    </script>
    <!-- /.container -->
{% endblock %}

konferencija/conference/templates/conference/konferencija_list.html
{% extends "base.html" %}

{% block content %}
<!-- Page Content -->
  <div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="text-center pt-5 mr-5">My Conferences</h1>
    <div class="row offset-md-1">
      <!-- Blog Entries Column -->
      <div class="col-md-10 col-sm-12 pt-5">
        {% for obj in object_list reversed  %}
        <!-- Blog Post -->
        <div class="card mb-5">
          <img class="card-img-top"  src="{{ obj.image.url }}" height="400" alt="Card image cap">
          <div class="card-body">
            <h2 class="card-title">{{ obj.name }}
              {% if request.user == obj.chairman %}
              [ Chairman ]
              {% endif %}
            </h2>
            <p class="card-text">{{ obj.summary }}</p>
            <a href="{{ obj.get_absolute_url }}" class="btn btn-secondary">Read More &rarr;</a>
          </div>
        </div>
        {% endfor %}
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
  </div>
{% endblock %}

konferencija/conference/templates/conference/radovi_list.html
{% extends "base.html" %}


{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Page Heading/Breadcrumbs -->
  <h1 class="mt-4 mb-3">Radovi
  </h1>


  <div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

      <!-- Blog Post -->
      {% for obj in object_list %}
      <div class="card mb-4">
        <div class="card-body">
          <div class="card-title">
            <h2>{{ obj.title|title }}</h2>
          </div>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
          <p class="float-right pr-5" style="font-size:2.3vh;">Uploader :     {{ obj.user_sekcija.user.username }} </p>
          <div class="row">
            <div class="ml-3">
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="path" value ="{{ obj.upload.url }}" />
                <button type="submit" class="btn btn-secondary">Display pdf</button>
              </form>
            </div>
          {% if request.user.is_superuser or bool %}
            <div class="ml-5">
            {% if obj.approved == 0 %}
            {% elif obj.approved == 1 %}
            <form method="post">
              {% csrf_token %}
              <div class="input-group mb-3 float-right">
              <select name = {{obj.id}}_choose>
                <option value="2">Odobreno</option>
                <option value="3">Odobreno uz malu doradu</option>
                <option value="4">Odobreno uz veću doradu</option>
                <option value="5">Odbijeno</option>
              </select>
              <div class="input-group-append">
              <button type="submit" class="btn btn-secondary">Ocijeni</button>
              </div>
              </div>
            </form>

            {% else %}
            <form method="post">
              {% csrf_token %}
              <div class="input-group mb-3 float-right">
              <select name = {{obj.id}}_choose>
                {% if obj.approved != 2 %}
                <option value="2">Odobreno</option>
                {% else %}
                <option selected value="2">Odobreno</option>
                {% endif %}
                {% if obj.approved != 3 %}
                <option value="3">Odobreno uz malu doradu</option>
                {% else %}
                <option selected value="3">Odobreno uz malu doradu</option>
                {% endif %}
                {% if obj.approved != 4 %}
                <option value="4">Odobreno uz veću doradu</option>
                {% else %}
                <option selected value="4">Odobreno uz veću doradu</option>
                {% endif %}
                {% if obj.approved != 5 %}
                <option value="5">Odbijeno</option>
                {% else %}
                <option selected value="5">Odbijeno</option>
                {% endif %}
              </select>
              <div class="input-group-append">
              <button type="submit" class="btn btn-secondary">Ocijeni</button>
              </div>
              </div>
            </form>
            {% endif %}
          </div>
          {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
      {% if object_list %}
      <div class="card mb-4">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {% for obj in object_list %}
            <input type="hidden" name="all" value ="{{ obj.upload.url }}" />
            {% endfor %}
            <button type="submit" class="btn btn-secondary" >Download all</button>
          </form>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
  <!-- /.row -->
    <a class="btn btn-outline-secondary" href="{% url 'conference:sekcija' pk=Id %}">Back</a>


</div>
<!-- /.container -->

{% endblock %}

konferencija/conference/templates/conference/recenzent_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <h2  class="container mb-5 text-center" >Recenzent approval</h2>
  {% for obj in recenzent_list %}
  <div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="{{ obj.user.username }}   {{ obj.sekcija.name|title }}" aria-label="Recipient's username" aria-describedby="basic-addon2" disabled>
  <div class="input-group-append">
    <form method="post">
      {% csrf_token %}
      <input type="hidden" name="user" value = "{{ obj.id }}"/>
      <input type="hidden" name="bool" value = "true"/>
      <button class="btn btn-outline-secondary" type="submit" style="border-radius: 0px;">Approve</button>
    </form>
    <form method="post">
      {% csrf_token %}
      <input type="hidden" name="user" value = "{{ obj.id }}"/>
      <input type="hidden" name="bool" value="false"/>
      <button class="btn btn-outline-secondary" style="border-radius: 0px 5px 5px 0px;" type="submit">Deny</button>
    </form>
  </div>
</div>
{% endfor %}
</div>
{% endblock %}

konferencija/conference/templates/conference/sekcija_create.html
{% extends "base.html" %}
{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Contact Form -->
  <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
  <div class="row">
    <div class="col-lg-8 mb-4 pt-5">
      <h3>{{Sekcija.name}} {{Konferencija.name}}</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% for obj in Konferencija.form %}
        <div class="pb-3">
          <p>{{ obj }}</p>
          <input class="form-control" type="text" name= 'question - {{ forloop.counter }}'>
        </div>
        {% endfor %}
        <button class="btn btn-secondary" type="submit">Create</button>
      </form>
  </div>
</div>
  </div>
  <!-- /.row -->
<!-- /.container -->
{% endblock %}

konferencija/conference/templates/conference/sekcija_detail.html
{% extends "base.html" %}

{% block content %}

<!-- Page Content -->
  <div class="container">
    <div class="empty-space">
    </div>
    <!-- Page Heading/Breadcrumbs -->
    <div class="row mb-5">
      <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">{{ object.name|title }} section</h2>
          <h4 class="section-subheading text-muted">This is the sections page. Here you can upload or search scientific papers.</h4>
      </div>
    </div>

    <!-- Marketing Icons Section -->
    <div class="row">
        {% if Bool and not registered.recenzent_approved %}
          <div class="col-lg-4 mb-4">
            <div class="card h-100">
              <h4 class="card-header">Upload paper</h4>
              <div class="card-body">
                <p class="card-text">Days left to upload: {{ Time }} days</p>
                {% if State %}
                <p class="card-text">Current state of paper: {{ State }} </p>
                <p class="card-text">Name of paper: {{ Rad.title|title }} </p>
                {% endif %}
              </div>
              <div class="card-footer">
                <a href="{% url 'conference:create_file' pk=registered.id %}" class="btn btn-secondary">Upload</a>
              </div>
            </div>
          </div>
        {% endif %}
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">Scientific papers</h4>
          <div class="card-body">
            <p class="card-text">Click here for an overview of the currently uploaded scientific papers</p>
          </div>
          <div class="card-footer">
            <a href="{% url 'conference:radovi_list' pk=registered.sekcija.id %}" class="btn btn-secondary">Search Papers</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
      <a class="btn btn-outline-secondary" href="{% url 'conference:detail' pk=Sekcija.konferencija.id %}">Back</a>

  </div>
  <!-- /.container -->
{% endblock %}